[package]
name = "aiid_js"
version = "0.0.1"
license = "Apache-2.0"

[lib]
name = "aiid_js"
crate-type = ["cdylib"]

[dependencies]
aiid = { path = "../../aiid" }
wasm-bindgen = "=0.2.40"
wee_alloc = "=0.4.4"
