[package]
name = "aiid_js"
authors = [ "AIngle Core Dev Team <devcore@aingle.ai>"]
version = "0.0.1"
license = "Apache-2.0"

[lib]
name = "aiid_js"
crate-type = ["cdylib"]

[dependencies]
aiid = "=0.0.2"
wasm-bindgen = "=0.2.40"
wee_alloc = "=0.4.4"
